import { create } from 'zustand';

export const useItemStore = create((set) => ({
  itemData: {
    name: '',
    description: '',
    image: null,
    thumbnail: null,
    store: '',
    category: '',
    subCategory: '',
    suitableFor: '',
    unit: '',
    stock: 0,
    price: 0,
    discountType: 'Percent',
    discount: 0,
    attributes: '',
    tags: [],
    isBasicMedicine: false,
    isPrescriptionRequired: false,
    store : '',
    category : '',
    subCategory : '',
    suitableFor : '',
    unit : '',
    maxQ : '',
    basicMed : true,
    prescriptionReq : true,
    price : '',
    discountType : '',
    totalStock : '',
    discount : '',
    attribute : '',
    tags : '',

  },
  setItemData: (field, value) => set((state) => ({
    itemData: {
      ...state.itemData,
      [field]: value,
    },
  })),
  resetItemData: () => set({
    itemData: {
      name: '',
      description: '',
      image: null,
      thumbnail: null,
      store: '',
      category: '',
      subCategory: '',
      suitableFor: '',
      unit: '',
      stock: 0,
      price: 0,
      discountType: 'Percent',
      discount: 0,
      attributes: '',
      tags: [],
      isBasicMedicine: false,
      isPrescriptionRequired: false,
      store : '',
      basicMed : true,
      prescriptionReq : true,
      price : '',
      discountType : '',
      totalStock : '',
      discount : '',
      attribute : '',
      tags : '',
    },
  }),
}));
